name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: helaili/jekyll-action@2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
